name: Build Windows Electron App

on:
  push:
    branches:
      - main

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm install

      - name: Build app
        run: npm run build --if-present

      - name: Package app
        run: npx electron-builder --win portable

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: MusicPlayer-windows-portable
          path: dist/*.exe
